[package]
name = "rust-wasm"
version = "0.1.0"
authors = ["Chris Ohk <utilForever@gmail.com>"]
edition = "2021"
description = "A template of Rust + WebAssembly with TypeScript (ğŸ¦€ + ğŸ•¸ï¸ = ğŸ’–)"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
